// Descriptive command mapping to prevent race conditions
// Frontend maps user selections to these descriptive commands

const MESSAGE_COMMANDS = {
  // Main Menu Commands
  PROCESS_DOCUMENT: 'PROCESS_DOCUMENT',
  SAVE_DOCUMENT: 'SAVE_DOCUMENT',
  GENERATE_REPORT: 'GENERATE_REPORT',
  VIEW_SUMMARY: 'VIEW_SUMMARY',
  SHARE_WITH_COLLEAGUES: 'SHARE_WITH_COLLEAGUES',
  HOW_IT_WORKS: 'HOW_IT_WORKS',
  CONTACT_SUPPORT: 'CONTACT_SUPPORT',
  UPGRADE_ACCOUNT: 'UPGRADE_ACCOUNT',
  MANAGE_SUBSCRIPTION: 'MANAGE_SUBSCRIPTION',
  
  // Category Selection Commands (for expense processing) - NEW 9 CATEGORIES
  CATEGORY_TRAVEL_ACCOMMODATION: 'CATEGORY_TRAVEL_ACCOMMODATION',
  CATEGORY_OFFICE_SUPPLIES: 'CATEGORY_OFFICE_SUPPLIES',
  CATEGORY_TECHNOLOGY_SOFTWARE: 'CATEGORY_TECHNOLOGY_SOFTWARE',
  CATEGORY_MEDICAL_HEALTHCARE: 'CATEGORY_MEDICAL_HEALTHCARE',
  CATEGORY_CHILDCARE: 'CATEGORY_CHILDCARE',
  CATEGORY_HOME_UTILITIES: 'CATEGORY_HOME_UTILITIES',
  CATEGORY_SHOPPING: 'CATEGORY_SHOPPING',
  CATEGORY_FOOD_GROCERIES: 'CATEGORY_FOOD_GROCERIES',
  CATEGORY_CUSTOM: 'CATEGORY_CUSTOM',

  // Save Receipt Category Commands - NEW 9 CATEGORIES
  SAVE_CATEGORY_INSURANCE: 'SAVE_CATEGORY_INSURANCE',
  SAVE_CATEGORY_WARRANTY: 'SAVE_CATEGORY_WARRANTY',
  SAVE_CATEGORY_TAX: 'SAVE_CATEGORY_TAX',
  SAVE_CATEGORY_MEDICAL_RECORDS: 'SAVE_CATEGORY_MEDICAL_RECORDS',
  SAVE_CATEGORY_APPLIANCE: 'SAVE_CATEGORY_APPLIANCE',
  SAVE_CATEGORY_TRANSPORTATION: 'SAVE_CATEGORY_TRANSPORTATION',
  SAVE_CATEGORY_TICKETS: 'SAVE_CATEGORY_TICKETS',
  SAVE_CATEGORY_MEDICAL_HEALTHCARE: 'SAVE_CATEGORY_MEDICAL_HEALTHCARE',
  SAVE_CATEGORY_CUSTOM: 'SAVE_CATEGORY_CUSTOM',
  
  // Receipt Choice Commands
  PROCESS_EXPENSE: 'PROCESS_EXPENSE',
  SAVE_EXPENSE: 'SAVE_EXPENSE',

  // Confirmation Commands
  SAVE_THIS_EXPENSE: 'SAVE_THIS_EXPENSE',

  // Confirmation Commands (NEW 3-BUTTON FLOW)
  EDIT_DETAILS: 'EDIT_DETAILS',
  RETAKE_DOCUMENT: 'RETAKE_DOCUMENT',
  
  // Receipt Conflict Commands
  SAVE_RECEIPT: 'SAVE_RECEIPT',
  CANCEL_RECEIPT: 'CANCEL_RECEIPT',

  // Unsaved Receipt Warning Commands
  SAVE_CURRENT_RECEIPT: 'SAVE_CURRENT_RECEIPT',
  CANCEL_CURRENT_RECEIPT: 'CANCEL_CURRENT_RECEIPT',
  VIEW_CURRENT_RECEIPT: 'VIEW_CURRENT_RECEIPT',

  // Missing File Handling Commands
  UPLOAD_NEW_RECEIPT: 'UPLOAD_NEW_RECEIPT',
  
  // Edit Menu Commands (WHATSAPP LIST)
  EDIT_MERCHANT_NAME: 'EDIT_MERCHANT_NAME',
  EDIT_DATE: 'EDIT_DATE',
  EDIT_TOTAL_AMOUNT: 'EDIT_TOTAL_AMOUNT',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  EDIT_TAX_AMOUNT: 'EDIT_TAX_AMOUNT',
  CHANGE_CURRENCY: 'CHANGE_CURRENCY', // Moved to edit sub-list
  DONE_EDITING: 'DONE_EDITING',
  
  // Continue Editing Commands
  EDIT_MORE_DETAILS: 'EDIT_MORE_DETAILS',
  SAVE_CHANGES: 'SAVE_CHANGES',
  CANCEL_CHANGES: 'CANCEL_CHANGES',
  
  // Report Generation Commands
  REPORT_THIS_MONTH: 'REPORT_THIS_MONTH',
  REPORT_LAST_2_MONTHS: 'REPORT_LAST_2_MONTHS',
  REPORT_LAST_3_MONTHS: 'REPORT_LAST_3_MONTHS',
  REPORT_ALL_TIME: 'REPORT_ALL_TIME',
  REPORT_BACK_TO_MENU: 'REPORT_BACK_TO_MENU',
  
  // Quality Tips Commands
  RETAKE_PHOTO: 'RETAKE_PHOTO',
  QUALITY_MAIN_MENU: 'QUALITY_MAIN_MENU',
  
  // How It Works Flow Commands
  TRY_TEXT_EXPENSE: 'TRY_TEXT_EXPENSE',
  SEE_PRICING: 'SEE_PRICING',
  REFER_FRIENDS: 'REFER_FRIENDS',
  HOW_WORKS_MAIN_MENU: 'HOW_WORKS_MAIN_MENU',
  
  // Pricing Flow Commands
  START_FREE: 'START_FREE',
  UPGRADE_TO_PRO: 'UPGRADE_TO_PRO',
  PRICING_MAIN_MENU: 'PRICING_MAIN_MENU',
  
  // Share Flow Commands
  SHARE_WHATSAPP_LINK: 'SHARE_WHATSAPP_LINK',
  SHARE_MAIN_MENU: 'SHARE_MAIN_MENU',
  
  // Currency Change Commands
  CURRENCY_USD: 'CURRENCY_USD',
  CURRENCY_INR: 'CURRENCY_INR',
  CURRENCY_EUR: 'CURRENCY_EUR',
  CURRENCY_GBP: 'CURRENCY_GBP',
  
  // Duplicate Detection Commands
  SKIP_DUPLICATE: 'SKIP_DUPLICATE',
  SAVE_AS_NEW_EXPENSE: 'SAVE_AS_NEW_EXPENSE',
  DUPLICATE_MAIN_MENU: 'DUPLICATE_MAIN_MENU',
  
  // Navigation Commands
  MAIN_MENU: 'MAIN_MENU',
  
  // Post Receipt Commands
  GET_EXCEL_FILE: 'GET_EXCEL_FILE',
  QUICK_OVERVIEW: 'QUICK_OVERVIEW',
  SEND_ANOTHER_RECEIPT: 'SEND_ANOTHER_RECEIPT',
  UPGRADE_PRO_PLAN: 'UPGRADE_PRO_PLAN',

  // Save Receipt Flow Commands
  SAVE_RECEIPT_VAULT: 'SAVE_RECEIPT_VAULT',
  ADD_ANOTHER_RECEIPT: 'ADD_ANOTHER_RECEIPT',
  DOWNLOAD_EXCEL_NOW: 'DOWNLOAD_EXCEL_NOW',
  
  // Global Commands (work from any state)
  GLOBAL_HELP: 'help',
  GLOBAL_RESET: 'reset',
  GLOBAL_SUMMARY: 'summary',
  GLOBAL_REPORT: 'report',
  GLOBAL_USAGE: 'usage',
  GLOBAL_UPGRADE: 'upgrade',
  GLOBAL_INFO: 'info'
};

// Mapping for backward compatibility with numeric inputs
// Frontend should gradually migrate to descriptive commands
const NUMERIC_TO_COMMAND_MAPPING = {
  // Context-based mapping (requires state checking as fallback)
  main_menu: {
    '1': MESSAGE_COMMANDS.PROCESS_DOCUMENT,
    '2': MESSAGE_COMMANDS.GENERATE_REPORT,
    '3': MESSAGE_COMMANDS.VIEW_SUMMARY,
    '4': MESSAGE_COMMANDS.SHARE_WITH_COLLEAGUES,
    '5': MESSAGE_COMMANDS.HOW_IT_WORKS,
    '6': MESSAGE_COMMANDS.CONTACT_SUPPORT,
    '7': MESSAGE_COMMANDS.UPGRADE_ACCOUNT
  },
  receipt_choice: {
    '1': MESSAGE_COMMANDS.PROCESS_DOCUMENT,
    '2': MESSAGE_COMMANDS.SAVE_DOCUMENT
  },
  category_selection: {
    '1': MESSAGE_COMMANDS.CATEGORY_TRAVEL_ACCOMMODATION,
    '2': MESSAGE_COMMANDS.CATEGORY_OFFICE_SUPPLIES,
    '3': MESSAGE_COMMANDS.CATEGORY_TECHNOLOGY_SOFTWARE,
    '4': MESSAGE_COMMANDS.CATEGORY_MEDICAL_HEALTHCARE,
    '5': MESSAGE_COMMANDS.CATEGORY_CHILDCARE,
    '6': MESSAGE_COMMANDS.CATEGORY_HOME_UTILITIES,
    '7': MESSAGE_COMMANDS.CATEGORY_SHOPPING,
    '8': MESSAGE_COMMANDS.CATEGORY_FOOD_GROCERIES,
    '9': MESSAGE_COMMANDS.CATEGORY_CUSTOM
  },
  save_category_selection: {
    '1': MESSAGE_COMMANDS.SAVE_CATEGORY_INSURANCE,
    '2': MESSAGE_COMMANDS.SAVE_CATEGORY_WARRANTY,
    '3': MESSAGE_COMMANDS.SAVE_CATEGORY_TAX,
    '4': MESSAGE_COMMANDS.SAVE_CATEGORY_MEDICAL_RECORDS,
    '5': MESSAGE_COMMANDS.SAVE_CATEGORY_APPLIANCE,
    '6': MESSAGE_COMMANDS.SAVE_CATEGORY_TRANSPORTATION,
    '7': MESSAGE_COMMANDS.SAVE_CATEGORY_TICKETS,
    '8': MESSAGE_COMMANDS.SAVE_CATEGORY_MEDICAL_HEALTHCARE,
    '9': MESSAGE_COMMANDS.SAVE_CATEGORY_CUSTOM
  },
  confirmation: {
    '1': MESSAGE_COMMANDS.SAVE_EXPENSE,
    '2': MESSAGE_COMMANDS.EDIT_DETAILS,
    '3': MESSAGE_COMMANDS.RETAKE_DOCUMENT
  },
  edit_menu: {
    '1': MESSAGE_COMMANDS.EDIT_MERCHANT_NAME,
    '2': MESSAGE_COMMANDS.EDIT_DATE,
    '3': MESSAGE_COMMANDS.EDIT_TOTAL_AMOUNT,
    '4': MESSAGE_COMMANDS.EDIT_CATEGORY,
    '5': MESSAGE_COMMANDS.EDIT_TAX_AMOUNT,
    '6': MESSAGE_COMMANDS.CHANGE_CURRENCY,
    '7': MESSAGE_COMMANDS.DONE_EDITING
  },
  continue_editing: {
    '1': MESSAGE_COMMANDS.EDIT_MORE_DETAILS,
    '2': MESSAGE_COMMANDS.SAVE_CHANGES,
    '3': MESSAGE_COMMANDS.CANCEL_CHANGES
  },
  report_generation: {
    '1': MESSAGE_COMMANDS.REPORT_THIS_MONTH,
    '2': MESSAGE_COMMANDS.REPORT_LAST_2_MONTHS,
    '3': MESSAGE_COMMANDS.REPORT_LAST_3_MONTHS,
    '4': MESSAGE_COMMANDS.REPORT_ALL_TIME,
    '5': MESSAGE_COMMANDS.MAIN_MENU
  },
  post_receipt: {
    '1': MESSAGE_COMMANDS.GENERATE_REPORT,
    '2': MESSAGE_COMMANDS.VIEW_SUMMARY,
    '3': MESSAGE_COMMANDS.MAIN_MENU
  },
  post_save_vault: {
    '1': MESSAGE_COMMANDS.ADD_ANOTHER_RECEIPT,
    '2': MESSAGE_COMMANDS.DOWNLOAD_EXCEL_NOW,
    '3': MESSAGE_COMMANDS.MAIN_MENU
  }
};

module.exports = {
  MESSAGE_COMMANDS,
  NUMERIC_TO_COMMAND_MAPPING
};